FROM jenkins/jenkins:lts

USER root

ENV JENKINS_USER=admin
ENV JENKINS_PASS=Octanetitan_3

COPY jenkins-plugins.txt /usr/share/jenkins/ref/jenkins-plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/jenkins-plugins.txt

# Jenkins runs all grovy files from init.groovy.d dir
# use this for creating default admin user
COPY initial-login.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY jenkins.yaml /usr/share/jenkins/ref
